[package]
name = "advent19"
version = "0.1.0"
authors = ["Will Normand <github@wnormand.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
